### ISSUE TITLE
Wrap All pyfiles in examples folder to run with pytest

### ISSUE THREAD

**Issue by kkappler** [kujaku11/mth5#13]
Basically wrap the code in "filename.py" as "def test_filename():", then if __name__=='__main__' it.

then create test_examples_folder.py .
and import all these test_filename functions and call them sequentially in there.

**Comment by kkappler** [comment]
make_mth5_file_from_xml.py    [DONE]
make_mth5_from_nims.py         [DONE]
make_mth5_from_z3d.py           [In Progress -- Test fails second time due to already existing file]
make_stationxml_from_mt.py    [DONE]

@kujaku11 can you take a look at make_mth5_from_z3d.py and run it twice in a row and see if you get this error the second time:
2021-01-11T20:29:03 [line 699] mth5.groups.base.Station.add_run - INFO: run b'sp02a' already exists, returning existing group.
Traceback (most recent call last):
  File "make_mth5_from_z3d.py", line 69, in <module>
    ch_list.append(run_group.from_channel_ts(mtts_obj))
  File "/home/kkappler/software/irismt/mth5/mth5/groups/master_station_run_channel.py", line 1341, in from_channel_ts
    channel_metadata=channel_ts_obj.metadata,
  File "/home/kkappler/software/irismt/mth5/mth5/groups/master_station_run_channel.py", line 1086, in add_channel
    **self.dataset_options,
  File "/home/kkappler/anaconda2/envs/aurora/lib/python3.6/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/kkappler/anaconda2/envs/aurora/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 137, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)

**Comment by kujaku11** [comment]
Yes, I get the same when run twice.  I fixed that issue in [Branch new_metadata](https://github.com/kujaku11/mth5/tree/new_metadata).  I was just finishing up that branch, I'll do a pull request later today, I think.

**Comment by kujaku11** [comment]
@kkappler fixed this by making mth5_test_data an importable module.
