### ISSUE TITLE
h5 file remains open on error

### ISSUE THREAD

**Issue by xandrd** [kujaku11/mth5#156]
If error occurred during the creation of h5 file, the file remains open and cannot be open again.

The issue can be reproduces if the following steps are executed in the Python terminal.
```python
from mth5.clients.make_mth5 import FDSN
import pandas as pd

request_df = pd.DataFrame(
        {
            "network": ["4P"],
            "station": ["ALW48"],
            "location": ["--"],
            "channel": ["*F*"],
            "start": ["2015-06-22T00:00:00"], #  ["2019-11-14T00:00:00"],
            "end":  ["2015-06-24T00:00:00:00"] # ["2019-11-15T00:00:00:00"]  #  Intentional error in the date
        }
    )

fdsn_object = FDSN(mth5_version='0.2.0', client="IRIS")
# Results an error (intentionally) and the file remains open
mth5_path = fdsn_object.make_mth5_from_fdsn_client(request_df, interact=False, path="./") 
```
`TypeError: '2015-06-24T00:00:00:00' could not be converted to type 'UTCDateTime'.`

```python
# Fixing the time
request_df.end = ["2015-06-24T00:00:00"]
# Results in error due to already open file
mth5_path = fdsn_object.make_mth5_from_fdsn_client(request_df, interact=False, path="./") 
```
```
2023-07-10 12:34:17,112 [line 607] mth5.mth5.MTH5.open_mth5 - WARNING: 4P_ALW48.h5 will be overwritten in 'w' mode
2023-07-10 12:34:17,115 [line 617] mth5.mth5.MTH5.open_mth5 - ERROR: Unable to create file (unable to truncate a file which is already open). Need to close any references to 4P_ALW48.h5 first. Then reopen the file in the preferred mode
Traceback (most recent call last):
  File "C:\work\Codes\SPEDAS\repo\mth5\mth5\mth5.py", line 611, in open_mth5
    self._initialize_file(mode)
  File "C:\work\Codes\SPEDAS\repo\mth5\mth5\mth5.py", line 653, in _initialize_file
    self.__hdf5_obj = h5py.File(self.__filename, mode)
  File "C:\work\Codes\SPEDAS\venvs\pyspedas39\lib\site-packages\h5py-3.8.0-py3.9-win-amd64.egg\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\work\Codes\SPEDAS\venvs\pyspedas39\lib\site-packages\h5py-3.8.0-py3.9-win-amd64.egg\h5py\_hl\files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 126, in h5py.h5f.create
OSError: Unable to create file (unable to truncate a file which is already open)
Traceback (most recent call last):
  File "C:\work\Codes\SPEDAS\venvs\pyspedas39\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-aa7a5bfc63ce>", line 1, in <module>
    mth5_path = fdsn_object.make_mth5_from_fdsn_client(request_df, interact=False, path="./")
  File "C:\work\Codes\SPEDAS\repo\mth5\mth5\clients\fdsn.py", line 135, in make_mth5_from_fdsn_client
    m.open_mth5(file_name, "w")
  File "C:\work\Codes\SPEDAS\repo\mth5\mth5\mth5.py", line 641, in open_mth5
    if not "channel_summary" in self.__hdf5_obj[self._root_path].keys():
TypeError: 'NoneType' object is not subscriptable
```

Suggestion:
- Handle exceptions
- Use `with` block
https://github.com/kujaku11/mth5/blob/ce814702c7116f5f0034f5d43a1392f61a2c3cd5/mth5/mth5.py#L653

OS: 'Windows-10-10.0.19045-SP0'
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
MTH5: commit hash: ce81470

**Comment by kujaku11** [comment]
Added context managing to `MTH5` and clients now use `with MTH5() as m:` to build MTH5s in PR #143

**Comment by xandrd** [comment]
I think the problem still persist (based on the code of [fc](https://github.com/kujaku11/mth5/tree/fc) branch). In [mth5/mth5/mth5.py](https://github.com/kujaku11/mth5/blob/ef382daa62baab8bad42221720c4f24e75a3b6ac/mth5/mth5.py#L658) the function `_initialize_file` creates a file object which is private `self.__hdf5_obj`. If `close` method is not called for this private `self.__hdf5_obj`, then the file remains open. My suggestion was added context managing in the `_initialize_file`. However, I'm not familiar with the internal architecture of mth5 and not sure if this is the right way.

**Comment by kujaku11** [comment]
@xandrd Interesting, I didn't think to put context managing in `MTH5._initialize_file`, as this is an internal method called when a file is opened.  If you put the context manager inside then the file will not be open to add groups to, so not sure how that would help.  

I was thinking the way you would use the context manager would be:

```
from mth5.mth5 import MTH5

with MTH5() as m:
   m.open_mth5("file_path/file_name.h5", "w")
   m.add_station("mt01")
```

Upon exit `MTH5.close_mth5()` is called with does flush and close the file and private variable `self.__hdf5_obj`

Does that make sense?
