### ISSUE TITLE
ValueError when calling RunTS calibrate() method in version 0.4.8 (works in earlier releases)

### ISSUE THREAD

**Issue by jameswilburlewis** [kujaku11/mth5#255]
Our application using mth5 worked properly with the past several releases, but now crashes when version 0.4.8 is used.  Here's a traceback:

```
Error
Traceback (most recent call last):
  File "/Users/jwl/PycharmProjects/pyspedas/pyspedas/mth5/tests/test_load_fdsn.py", line 118, in test02_load_fdsn_basic
    load_fdsn(network="4P", station="REU49", trange=[date_start, date_end])
  File "/Users/jwl/PycharmProjects/pyspedas/pyspedas/mth5/load_fdsn.py", line 264, in load_fdsn
    run_ts = run_ts.calibrate()
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/mth5/timeseries/run_ts.py", line 1051, in calibrate
    new_run.add_channel(calibrated_ch_ts)
  File "/Users/jwl/PycharmProjects/pyspedas/venv/lib/python3.9/site-packages/mth5/timeseries/run_ts.py", line 765, in add_channel
    raise ValueError(msg)
ValueError: Channel sample rate is not correct, current 0.0 input 1.0

```

I think I see what the problem might be: in the calibrate() method, we have this code:

```
        new_run = RunTS()
        new_run.run_metadata = self.run_metadata
        new_run.station_metadata = self.station_metadata

        for channel in self.channels:
            ch_ts = getattr(self, channel)
            calibrated_ch_ts = ch_ts.remove_instrument_response(**kwargs)
            new_run.add_channel(calibrated_ch_ts)
        return new_run

```

And in the add_channel() method:

```
        ### need to validate the channel to make sure sample rate is the same
        if c.sample_rate != self.sample_rate:
            msg = (
                f"Channel sample rate is not correct, current {self.sample_rate} "
                + f"input {c.sample_rate}"
            )
            self.logger.error(msg)
            raise ValueError(msg)

```

add_channel() is being called on the newly constructed RunTS object new_run in calibrate().  The run_metadata and station_metadata fields are initialized from the original RunTS object, but it looks to me like the sample_rate field is defaulting to 0.0, rather than being assigned from the original RunTS object self.sample_rate .

I will test this theory and submit a PR if I can get it working again....

**Update:**   After forking the repo and using it for my test code, I see that JP committed some changes yesterday that seem to have fixed the issue.  I hope there will be a new release coming soon!

**Comment by jameswilburlewis** [comment]
Confirmed fixed in version 0.4.9
